name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Blog from Markdown Files
        uses: kamranahmedse/github-pages-blog-action@v0.0.10
        with:
            branch: gh-pages # Optional branch for GitHub Pages
            token: ${{secrets.GITPAGE_PAT}}
